name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    env:
      python_ver: 3.11

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python_ver }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_ver }}
          architecture: "x64"
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - run: echo ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          zip -r flow.launcher.plugin.used-by.zip . -x '*.git*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "flow.launcher.plugin.used-by.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
